export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ?? "https://etobo.tech";

export const siteName = "Elver Tobo";

export const pirschCode = "CYUrmtH7kcB30a93crH3x6VuswShdckE";

export const socialLinks = {
  email: "contact@etobo.tech",
  github: "https://github.com/etobo-dev",
  gitlab: "https://gitlab.com/elverytr",
  linkedin: "https://www.linkedin.com/in/elver-tobo/",
  medium: "https://articles.etobo.tech",
  x: "https://x.com/_etobo_",
  credly: "https://www.credly.com/users/elver-tobo/badges/credly",
} as const;

/** Skills and topics for JSON-LD / AI discovery (English labels). */
export const seoKnowsAbout = [
  "Cloud architecture",
  "AWS",
  "Serverless architecture",
  "Infrastructure as Code",
  "Artificial Intelligence",
  "Application security",
  "Secure software development",
  "AWS Lambda",
  "Retrieval-Augmented Generation",
  "AI agents",
  "LangChain",
  "LangGraph",
  "Amazon S3",
  "Amazon EC2",
  "Amazon RDS",
  "Amazon DynamoDB",
  "Amazon ECS",
  "API Gateway",
  "Terraform",
  "Docker",
  "GitLab CI/CD",
  "Backend engineering",
  "Python",
  "FastAPI",
  "TypeScript",
  "Next.js",
  "PostgreSQL",
] as const;

export const seoKeywords = {
  en: [
    "Elver Tobo",
    "cloud architect",
    "AWS architect",
    "cloud engineer",
    "AI engineer",
    "AWS engineer",
    "serverless architect",
    "application security",
    "AWS certified",
    "secure software development",
    "RAG engineer",
    "LangChain",
    "LangGraph",
    "security developer",
    "Terraform",
    "Docker",
    "Python developer",
    "hire cloud architect",
    "remote software engineer",
    "GitLab CI/CD",
    "NotiCrypt",
    "Knowforge",
    "etobo.tech",
  ],
  es: [
    "Elver Tobo",
    "cloud architect",
    "arquitecto cloud",
    "arquitecto AWS",
    "ingeniero cloud",
    "ingeniero IA",
    "ingeniero AWS",
    "arquitecto serverless",
    "seguridad de aplicaciones",
    "certificado AWS",
    "desarrollo de software seguro",
    "ingeniero RAG",
    "LangChain",
    "LangGraph",
    "security developer",
    "Terraform",
    "Docker",
    "desarrollador Python",
    "contratar cloud architect",
    "ingeniero de software remoto",
    "GitLab CI/CD",
    "NotiCrypt",
    "Knowforge",
    "etobo.tech",
  ],
} as const;
