export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ?? "https://etobo.tech";

export const siteName = "Elver Tobo";

export const pirschCode = "CYUrmtH7kcB30a93crH3x6VuswShdckE";

export const socialLinks = {
  email: "contact@etobo.tech",
  github: "https://github.com/etobo-dev",
  gitlab: "https://gitlab.com/elverytr",
  linkedin: "https://www.linkedin.com/in/elver-tobo/",
  medium: "https://articles.etobo.tech",
  x: "https://x.com/_etobo_",
  credly: "https://www.credly.com/users/elver-tobo/badges/credly",
} as const;

/** Skills and topics for JSON-LD / AI discovery (English labels). */
export const seoKnowsAbout = [
  "Backend engineering",
  "Python",
  "FastAPI",
  "AWS",
  "AWS Lambda",
  "Amazon S3",
  "Amazon EC2",
  "Amazon RDS",
  "Amazon DynamoDB",
  "Amazon ECS",
  "API Gateway",
  "Serverless architecture",
  "Cloud architecture",
  "Infrastructure as Code",
  "Terraform",
  "Docker",
  "GitLab CI/CD",
  "Application security",
  "Secure software development",
  "Artificial Intelligence",
  "Retrieval-Augmented Generation",
  "AI agents",
  "LangChain",
  "LangGraph",
  "TypeScript",
  "Next.js",
  "PostgreSQL",
] as const;

export const seoKeywords = {
  en: [
    "Elver Tobo",
    "backend engineer",
    "backend developer",
    "Python developer",
    "FastAPI developer",
    "AWS engineer",
    "AWS certified",
    "serverless engineer",
    "cloud engineer",
    "software engineer for hire",
    "hire backend engineer",
    "remote software engineer",
    "application security",
    "Terraform",
    "Docker",
    "GitLab CI/CD",
    "AI engineer",
    "RAG engineer",
    "LangChain",
    "LangGraph",
    "NotiCrypt",
    "Knowforge",
    "etobo.tech",
  ],
  es: [
    "Elver Tobo",
    "ingeniero backend",
    "desarrollador backend",
    "desarrollador Python",
    "desarrollador FastAPI",
    "ingeniero AWS",
    "certificado AWS",
    "ingeniero serverless",
    "ingeniero cloud",
    "ingeniero de software para contratar",
    "contratar ingeniero backend",
    "ingeniero de software remoto",
    "seguridad de aplicaciones",
    "Terraform",
    "Docker",
    "GitLab CI/CD",
    "ingeniero IA",
    "ingeniero RAG",
    "LangChain",
    "LangGraph",
    "NotiCrypt",
    "Knowforge",
    "etobo.tech",
  ],
} as const;
